@startuml 

component core{
    package exciter.core
}

component ui{
    package exciter.ui
}

component json{
    package exciter.json
    
}

component javafx{
    package javafx.controls
    package javafx.fxml
}

component restserver{
    package exciter.restserver

}

component user {
    package jackson
    package exciter.user

}
component json.simple{

}

component jackson {
}

component "springboot/restserver" as springboot.restserver {
	package exciter.springboot.restserver
}

exciter.springboot.restserver ..> exciter.core
exciter.springboot.restserver ..> exciter.json

component "spring boot" as springboot {
}

component okHTTP {

}
exciter.restserver ..> okHTTP
springboot.restserver ..> springboot
exciter.restserver ..> exciter.json
exciter.restserver ..>exciter.core
exciter.ui ..> exciter.core
exciter.ui ..> javafx.controls
exciter.ui ..> javafx.fxml
exciter.ui ..> exciter.user


exciter.ui ..> jackson
exciter.json ..> json.simple




@enduml
