@startuml restserver

class ServerController {
    -Exciter excite
    -FileHandler fileHandler
    -MessageHandler messageHandler

}

class ExciterApplication{
    +Exciter excite
    +FileHandler fileHandler

}

class User{

}

class BotUser{

}

class Exciter{

}

class FileHandler{

}

class MessageHandler{
    
}

class App{
}

class ClientHandler{

}

class LoginController{

}

class SignUpController{

}

class PrimaryController{

}
class SecondaryController{

}
class MatchController{

}

class Chat{

}

BotUser --> User
User -->Exciter
Exciter --> ServerController
User --> FileHandler
FileHandler --> ServerController
MessageHandler --> ServerController
Exciter --> ExciterApplication
FileHandler --> ExciterApplication
User --> App
LoginController --> ClientHandler
SignUpController --> ClientHandler
PrimaryController --> ClientHandler
SecondaryController --> ClientHandler
MatchController --> ClientHandler
User --> LoginController
User --> MatchController
Chat --> MatchController
User --> PrimaryController
User --> SecondaryController
User --> SignUpController
Chat --> MessageHandler






@enduml
