@startuml restserver

class ServerController {
    -Exciter excite
    -FileHandler fileHandler
    -MessageHandler messageHandler
    +String index()


}

class ExciterApplication{
    #Exciter excite
    -FileHandler fileHandler
    +main(String[])


}






@enduml
