@startuml restserver

class ServerController {
    -Exciter excite
    -FileHandler fileHandler
    -MessageHandler messageHandler
    +String index()


}

class ExciterApplication{
    #Exciter excite
    -FileHandler fileHandler
    +main(String[])


}

class User{
    -UUID id
    -String name
    -int age
    -String userInformation
    -String email
    -Map<String, Integer> likedUser
    -List<String> matches
    -String password
    -int imageId
    +boolean containsPreviousMatch(String)
    +void fireOnLike(String)
    +void resetUserMatch(String)
    +void resetUserMatchToOne(String)
    +void checkIfMatch(User)
    +boolean haveLikedUser(String)
}

class BotUser{
    -boolean likeBack
    -List<String> replies
    + String reply()

}

class Exciter{
    -List<User> allUsers
    +void addUser(User)
    +void addUsers(List<User>)
    +void addSomePlaceHolderUsers()
    +User getNextRandomUser(List<User>)
    +List<User> getTwoUniqueUsers(User)
    -List<User> pickNrandom(List<User>, int)
    +List<User> getUsersFromList(List<String>)
    +User getUserByEmail(String)
    +User getUserById(UUID)
    +void clearUser(User)
    +int getLikeCount(User, User)
    +void removeFromAllUsers(User)
    +void settAllUsers(ArrayList<User>)
    +boolean likePerson(User, User)
    +void resetLikes(User, User)
    +List<String> getUserMatches(User)

}

class FileHandler{
    String url
    -JSONParser ParticipantStereotypeFontColor
    +void saveUser(List<User>)
    +void createFile()
    +List<User> readUsers()
    +List<String> parseJsonList(JSONArray)
    +Map<String, Integer> parseJsonMap(JSONObject)
    +User getUser(String)
    +User getUserById(UUID)
    +Map<String, Integer> getLikedUsers(UUID)

}

class MessageHandler{
    String url
    -JSONParser parser
    +void createFile()
    +void saveChat(Chat)
    +List<Chat> getChats()
    -List<Map<String, String>> getMessages(JSONObject)
    -void removeFromChat(String, String, List<Chat>)
    +Chat getChat(String, String)
}

class App{
}

class ClientHandler{
    OkHttpClient client
    ObjectMappper mapper
    String url
    +boolean pingServer()
    +User discardCard(User, User, User)
    +User createAccount(User, String)
    +User login(String, String)
    +List<User> getMatches(User)
    +User updateInformation(User)
    +User updatePassword(User, String)
    +List<User> getTwoUsers(User)
    +int getUserLikeCount(User, User)
    +User getUser(User, List<User>)
    +Chat sendMessage(User, User, String)
    +Chat getChat(User, User)
    +boolean deleteUser(User)
}

class LoginController{
    -ClientHandler clientHandler
    +void initialize()
    +void handleLogin(ActionEvent event)
    -void changeUser(User)
    void onSwitchToSignUp(MouseEvent event)
    +void addUser(String, String)

}

class SignUpController{
     -ClientHandler clientHandler
     void initialize()
     +void clearFields()
     -boolean validName(String)
     -boolean isNumeric(String)
     -boolean emailValidator(String)
     void onSwitchToLogin(MouseEvent event)
     void handleCreateAccount(ActionEvent event)
     +void addUser(User, String)


}

class PrimaryController{
    -ClientHandler clientHandler
    -User user
    -int NumMatches
    -User leftUser
    -User rightUser
    -ImageController imageController
    -void switchToSecondary(MouseEvent event)
    -void switchToMatch(MouseEvent event)
    -void hoverButton(Node)
    void onDiscardLeftCard()
    void onDiscardRightCard
    +void cardLiked(Pane, Pane)
    +TranslateTransition translateCardY(Pane, double, boolean)
    +FadeTransistion animateScore(String, boolean)
    void refresh()
    +void setNextUsers()
    -void dragY(Pane)
    +List<User> getOnScreenUsers()
    +Circle getNotificationCircle()
    +ImageController getImageController()
}
class SecondaryController{
    -ClientHandler clientHandler
    -User user
    -ImageController imageController
    +void switchToPrimary(MouseEvent event)
    -void hoberButton(Group)
    -void selectAvatar()
    void updatePreview()
    +void signOut(MouseEvent event)
    void save()
    void initialize(URL, ResourceBundle)

}
class MatchController{
    -int chatId
    -ImageController imageController
    -ClientHandler clientHandler
    -User user
    -User user1
    -double height
    -List<User> matches
    +void switchToPrimary(MouseEvent)
    +void initialize(URL, ResourceBundle
    +void refresh()
    +void sendMessage()
    -HBox createMessage(String, Boolean)
    -void hoverButton(Node)
    -void clickButton(Group, User, int)
    #Group createMatchCard(User)
    -void updateCardPane(User)
    +void animateProfile()
    -void fillChat(User, User)
    -String stringFormatter(String)
    +VBox getMatchBox()
    +VBox gettextBox()
}

class Chat{
    -String user1
    -String user2
    -List<Map<String, String>> messages
    +void sendMessage(String, String)

}

BotUser --|> User
Exciter --> User
FileHandler --> User
Chat--> User
MessagesHandler --> Chat
ClientHandler ..> User
LoginController --> ClientHandler
SignUpController --> ClientHandler
PrimaryController --> ClientHandler
SecondaryController --> ClientHandler
MatchController --> ClientHandler




@enduml
